#################### Music Request
GET http://localhost:3000/api/music HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/api/music HTTP/1.1
content-type: application/json

{
    "audioUrl": "https://audiourl.mp3",
    "coverUrl": "https://myurl-image.png",
    "gender": "RAP",
    "theme": "RAP Theme",
    "title": "Minha música"
}
#################### User Request
GET http://localhost:3000/api/user HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
    "name": "Joe Dawn",
    "password": "123456"
}
#################### Playlist Request
GET http://localhost:3000/api/playlist HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/api/playlist HTTP/1.1
content-type: application/json

{
    "coverUrl": "https://myurl-image.png",
    "description": "This is playlist",
    "gender": "RAPs",
    "title": "The Best RAPs"
}